/*-------------------------------------------------------------------------*\
|                                                                           |
|  FILE: EXAFEATURE.H                                                       |
|                                                                           |
|                                                                           |
|  RTPatch Server Feature Selection Header File                             |
|                                                                           |
|                                                                           |
|  (C) Copyright Pocket Soft, Inc. 2011.  All Rights Reserved.              |
|                                                                           |
\*-------------------------------------------------------------------------*/
# ifndef EXAFEATURE_INCLUDED
# define EXAFEATURE_INCLUDED
/*
Possible features - 
EXAPATCH_BACKUP_SUPPORT
EXAPATCH_HISTORY_SUPPORT
EXAPATCH_REGISTRY_SUPPORT
EXAPATCH_REGISTRYSCRIPT_SUPPORT
EXAPATCH_HOOK_SUPPORT
EXAPATCH_BYTE_SUPPORT
EXAPATCH_SYSTEM_SUPPORT
EXAPATCH_PASSWORD_SUPPORT
EXAPATCH_COMMENT_SUPPORT
EXAPATCH_LINK_SUPPORT
EXAPATCH_LIST_SUPPORT
EXAPATCH_ONEFILE_SUPPORT
EXAPATCH_VERIFYONLY_SUPPORT
EXAPATCH_UNDO_SUPPORT
EXAPATCH_ADDWITHFILE_SUPPORT
EXAPATCH_PATHSEARCH_SUPPORT
EXAPATCH_SUBDIRSEARCH_SUPPORT
EXAPATCH_ADDFILE_SUPPORT
EXAPATCH_DISKSPACE_SUPPORT
EXAPATCH_DEVCHECK_SUPPORT
EXAPATCH_TEMPFILE_SUPPORT
EXAPATCH_EH_SUPPORT
EXAPATCH_SELFREG_SUPPORT [includes shared files]
EXAPATCH_DEFAULTSTREAM_SUPPORT
EXAPATCH_CACHEDSTREAM_SUPPORT
EXAPATCH_COMPOSITESTREAM_SUPPORT
EXAPATCH_SPECIALSTREAM_SUPPORT
EXAPATCH_CHECKSUM_SUPPORT
EXAPATCH_ALLOWDELAY_SUPPORT
EXAPATCH_ARCHIVE_SUPPORT
EXAPATCH_CONTAINER_SUPPORT
EXAPATCH_UPDATELINK_SUPPORT
EXAPATCH_OWNERGROUP_SUPPORT
EXAPATCH_TEMPDIR_SUPPORT
EXAPATCH_FORCECOPY_SUPPORT
EXAPATCH_LOCKDIR_SUPPORT
EXAPATCH_ACLCACHE_SUPPORT
EXAPATCH_IN_PLACE_SUPPORT
EXAPATCH_DETAILED_APPLY_API_SUPPORT
EXAPATCH_DETAILED_BUILD_API_SUPPORT

EXAPATCH_SILENT_UNSUPPORT
*/
# ifdef ATTOPATCH
/* pretty much nothing included in ATTOPATCH */
#  define EXAPATCH_DETAILED_BUILD_API_SUPPORT
#  ifdef EXAPATCH_IN_PLACE_SUPPORT
#   define EXAPATCH_CHECKSUM_SUPPORT
# endif
/*#  define EXAPATCH_SPECIALSTREAM_SUPPORT*/
# else
#  ifdef DUMP_ONLY
/* everything is included in dump/verify utilities */
#   define EXAPATCH_BACKUP_SUPPORT
#   define EXAPATCH_HISTORY_SUPPORT
#   define EXAPATCH_REGISTRY_SUPPORT
#   define EXAPATCH_REGISTRYSCRIPT_SUPPORT
#   define EXAPATCH_HOOK_SUPPORT
#   define EXAPATCH_BYTE_SUPPORT
#   define EXAPATCH_SYSTEM_SUPPORT
#   define EXAPATCH_SUBDIR_SUPPORT
#   define EXAPATCH_PASSWORD_SUPPORT
#   define EXAPATCH_COMMENT_SUPPORT
#   define EXAPATCH_LINK_SUPPORT
#   define EXAPATCH_LIST_SUPPORT
#   define EXAPATCH_ONEFILE_SUPPORT
#   define EXAPATCH_VERIFYONLY_SUPPORT
#   define EXAPATCH_UNDO_SUPPORT
#   define EXAPATCH_ADDWITHFILE_SUPPORT
#   define EXAPATCH_PATHSEARCH_SUPPORT
#   define EXAPATCH_SUBDIRSEARCH_SUPPORT
#   define EXAPATCH_ADDFILE_SUPPORT
#   define EXAPATCH_DISKSPACE_SUPPORT
#   define EXAPATCH_DEVCHECK_SUPPORT
#   define EXAPATCH_TEMPFILE_SUPPORT
#   define EXAPATCH_EH_SUPPORT
#   define EXAPATCH_SELFREG_SUPPORT
#   define EXAPATCH_DEFAULTSTREAM_SUPPORT
#   define EXAPATCH_CACHEDSTREAM_SUPPORT
#   define EXAPATCH_COMPOSITESTREAM_SUPPORT
#   define EXAPATCH_CHECKSUM_SUPPORT
#   define EXAPATCH_VERBOSE_SUPPORT
#   define EXAPATCH_ALLOWDELAY_SUPPORT
#   define EXAPATCH_ARCHIVE_SUPPORT
#   define EXAPATCH_UPDATELINK_SUPPORT
#   define EXAPATCH_OWNERGROUP_SUPPORT
#   define EXAPATCH_TEMPDIR_SUPPORT
#   define EXAPATCH_FORCECOPY_SUPPORT
#   define EXAPATCH_LOCKDIR_SUPPORT
/* #   define EXAPATCH_CONTAINER_SUPPORT */
/* #   define EXAPATCH_ACLCACHE_SUPPORT */
/* # define EXAPATCH_IN_PLACE_SUPPORT */
#   define EXAPATCH_DETAILED_APPLY_API_SUPPORT
#   define EXAPATCH_DETAILED_BUILD_API_SUPPORT
#  else
#   ifdef _WIN32
		// Win32
#    define EXAPATCH_BACKUP_SUPPORT
#    define EXAPATCH_HISTORY_SUPPORT
#    define EXAPATCH_REGISTRY_SUPPORT
#    define EXAPATCH_REGISTRYSCRIPT_SUPPORT
#    define EXAPATCH_HOOK_SUPPORT
#    define EXAPATCH_BYTE_SUPPORT
#    define EXAPATCH_SYSTEM_SUPPORT
#    define EXAPATCH_SUBDIR_SUPPORT
#    define EXAPATCH_PASSWORD_SUPPORT
#    define EXAPATCH_COMMENT_SUPPORT
#    define EXAPATCH_LINK_SUPPORT
#    define EXAPATCH_LIST_SUPPORT
#    define EXAPATCH_ONEFILE_SUPPORT
#    define EXAPATCH_VERIFYONLY_SUPPORT
#    define EXAPATCH_UNDO_SUPPORT
#    define EXAPATCH_ADDWITHFILE_SUPPORT
#    define EXAPATCH_PATHSEARCH_SUPPORT
#    define EXAPATCH_SUBDIRSEARCH_SUPPORT
#    define EXAPATCH_ADDFILE_SUPPORT
#    define EXAPATCH_DISKSPACE_SUPPORT
#    define EXAPATCH_DEVCHECK_SUPPORT
#    define EXAPATCH_TEMPFILE_SUPPORT
#    define EXAPATCH_EH_SUPPORT
#    define EXAPATCH_SELFREG_SUPPORT
#    define EXAPATCH_DEFAULTSTREAM_SUPPORT
#    define EXAPATCH_CACHEDSTREAM_SUPPORT
#    define EXAPATCH_COMPOSITESTREAM_SUPPORT
#    define EXAPATCH_CHECKSUM_SUPPORT
#    define EXAPATCH_VERBOSE_SUPPORT
#    define EXAPATCH_ALLOWDELAY_SUPPORT
#    define EXAPATCH_ARCHIVE_SUPPORT
#    define EXAPATCH_UPDATELINK_SUPPORT
#		 define EXAPATCH_OWNERGROUP_SUPPORT
#    define EXAPATCH_CONTAINER_SUPPORT
#    define EXAPATCH_TEMPDIR_SUPPORT
#    define EXAPATCH_FORCECOPY_SUPPORT
#    define EXAPATCH_LOCKDIR_SUPPORT
#    define EXAPATCH_ACLCACHE_SUPPORT
#    define EXAPATCH_IN_PLACE_SUPPORT
#    define EXAPATCH_DETAILED_APPLY_API_SUPPORT
#    define EXAPATCH_DETAILED_BUILD_API_SUPPORT
//#   define EXAPATCH_SILENT_UNSUPPORT
//#  define EXAPATCH_SPECIALSTREAM_SUPPORT
#   else
		// Non-Win32
#    ifdef __APPLE__
		// Mac
#     define EXAPATCH_BACKUP_SUPPORT
#     define EXAPATCH_HISTORY_SUPPORT
//#     define EXAPATCH_REGISTRY_SUPPORT
//#     define EXAPATCH_REGISTRYSCRIPT_SUPPORT
#     define EXAPATCH_HOOK_SUPPORT
#     define EXAPATCH_BYTE_SUPPORT
#     define EXAPATCH_SYSTEM_SUPPORT
#     define EXAPATCH_SUBDIR_SUPPORT
#     define EXAPATCH_PASSWORD_SUPPORT
#     define EXAPATCH_COMMENT_SUPPORT
#     define EXAPATCH_LINK_SUPPORT
#     define EXAPATCH_LIST_SUPPORT
#     define EXAPATCH_ONEFILE_SUPPORT
#     define EXAPATCH_VERIFYONLY_SUPPORT
#     define EXAPATCH_UNDO_SUPPORT
#     define EXAPATCH_ADDWITHFILE_SUPPORT
#     define EXAPATCH_PATHSEARCH_SUPPORT
#     define EXAPATCH_SUBDIRSEARCH_SUPPORT
#     define EXAPATCH_ADDFILE_SUPPORT
#     define EXAPATCH_DISKSPACE_SUPPORT
#     define EXAPATCH_DEVCHECK_SUPPORT
#     define EXAPATCH_TEMPFILE_SUPPORT
#     define EXAPATCH_EH_SUPPORT
//#     define EXAPATCH_SELFREG_SUPPORT
#     define EXAPATCH_DEFAULTSTREAM_SUPPORT
#     define EXAPATCH_CACHEDSTREAM_SUPPORT
#     define EXAPATCH_COMPOSITESTREAM_SUPPORT
#     define EXAPATCH_CHECKSUM_SUPPORT
#     define EXAPATCH_VERBOSE_SUPPORT
#     define EXAPATCH_ALLOWDELAY_SUPPORT
#     define EXAPATCH_ARCHIVE_SUPPORT
#     define EXAPATCH_UPDATELINK_SUPPORT
//#  define EXAPATCH_OWNERGROUP_SUPPORT
//#     define EXAPATCH_TEMPDIR_SUPPORT
//#     define EXAPATCH_FORCECOPY_SUPPORT
#     define EXAPATCH_CONTAINER_SUPPORT
#     define EXAPATCH_LOCKDIR_SUPPORT
//#    define EXAPATCH_ACLCACHE_SUPPORT
# define EXAPATCH_IN_PLACE_SUPPORT
#     define EXAPATCH_DETAILED_APPLY_API_SUPPORT
#     define EXAPATCH_DETAILED_BUILD_API_SUPPORT
//#    define EXAPATCH_SILENT_UNSUPPORT
#   else
		// non-Win32, non-Apple - currently, Linux/Unix
#     define EXAPATCH_BACKUP_SUPPORT
#     define EXAPATCH_HISTORY_SUPPORT
//#     define EXAPATCH_REGISTRY_SUPPORT
//#     define EXAPATCH_REGISTRYSCRIPT_SUPPORT
#     define EXAPATCH_HOOK_SUPPORT
#     define EXAPATCH_BYTE_SUPPORT
#     define EXAPATCH_SYSTEM_SUPPORT
#     define EXAPATCH_SUBDIR_SUPPORT
#     define EXAPATCH_PASSWORD_SUPPORT
#     define EXAPATCH_COMMENT_SUPPORT
#     define EXAPATCH_LINK_SUPPORT
#     define EXAPATCH_LIST_SUPPORT
#     define EXAPATCH_ONEFILE_SUPPORT
#     define EXAPATCH_VERIFYONLY_SUPPORT
#     define EXAPATCH_UNDO_SUPPORT
#     define EXAPATCH_ADDWITHFILE_SUPPORT
#     define EXAPATCH_PATHSEARCH_SUPPORT
#     define EXAPATCH_SUBDIRSEARCH_SUPPORT
#     define EXAPATCH_ADDFILE_SUPPORT
#     define EXAPATCH_DISKSPACE_SUPPORT
#     define EXAPATCH_DEVCHECK_SUPPORT
#     define EXAPATCH_TEMPFILE_SUPPORT
#     define EXAPATCH_EH_SUPPORT
//#     define EXAPATCH_SELFREG_SUPPORT
#     define EXAPATCH_DEFAULTSTREAM_SUPPORT
#     define EXAPATCH_CACHEDSTREAM_SUPPORT
#     define EXAPATCH_COMPOSITESTREAM_SUPPORT
#     define EXAPATCH_CHECKSUM_SUPPORT
#     define EXAPATCH_VERBOSE_SUPPORT
#     define EXAPATCH_ALLOWDELAY_SUPPORT
#     define EXAPATCH_ARCHIVE_SUPPORT
#			define EXAPATCH_OWNERGROUP_SUPPORT
#     define EXAPATCH_UPDATELINK_SUPPORT
#     define EXAPATCH_CONTAINER_SUPPORT
#     define EXAPATCH_TEMPDIR_SUPPORT
#     define EXAPATCH_FORCECOPY_SUPPORT
#     define EXAPATCH_LOCKDIR_SUPPORT
//#    define EXAPATCH_ACLCACHE_SUPPORT
# define EXAPATCH_IN_PLACE_SUPPORT
#     define EXAPATCH_DETAILED_APPLY_API_SUPPORT
#     define EXAPATCH_DETAILED_BUILD_API_SUPPORT
//#    define EXAPATCH_SILENT_UNSUPPORT
#    endif
#    endif
#   endif
#  endif

/* enforce dependencies */
#  if !defined( EXAPATCH_ADDFILE_SUPPORT ) && defined( EXAPATCH_ADDWITHFILE_SUPPORT)
#   undef EXAPATCH_ADDWITHFILE_SUPPORT
#  endif
#  if !defined( EXAPATCH_DISKSPACE_SUPPORT ) && defined( EXAPATCH_DEVCHECK_SUPPORT )
#   undef EXAPATCH_DEVCHECK_SUPPORT
#  endif
#  if !defined( EXAPATCH_DEFAULTSTREAM_SUPPORT ) && defined( EXAPATCH_CHECKSUM_SUPPORT )
#   undef EXAPATCH_CHECKSUM_SUPPORT
#  endif
# endif
